#!/bin/bash
# Refuse edits to generated output. The book is compiled, not hand-written: an edit
# here is silently destroyed on the next build, which is worse than one that fails
# loudly.
INPUT=$(cat)
FILE=$(echo "$INPUT" | jq -r '.tool_input.file_path // empty')
FILE="${FILE//\\//}"

case "$FILE" in
  */build/*)
    echo "Blocked: build/ is generated by build.py. Edit chapters/*.md or assets/ instead, then rebuild." >&2
    exit 2
    ;;
  "$CLAUDE_PROJECT_DIR"/index.html|index.html)
    # The book moved here when it started publishing at the site root. An edit
    # here is both destroyed by the next build and live on the site until then.
    echo "Blocked: index.html is the built book. Edit chapters/*.md or assets/ instead, then run python build.py." >&2
    exit 2
    ;;
esac
exit 0
