#!/bin/bash
# Refuse edits to generated output. The book is compiled, not hand-written: an edit
# here is silently destroyed on the next build, which is worse than one that fails
# loudly.
INPUT=$(cat)
FILE=$(echo "$INPUT" | jq -r '.tool_input.file_path // empty')
FILE="${FILE//\\//}"

case "$FILE" in
  */build/*)
    echo "Blocked: build/ is generated by build.py. Edit chapters/*.md or assets/ instead, then rebuild." >&2
    exit 2
    ;;
esac
exit 0
